# Generated by Django 3.2.8 on 2021-11-20 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urlshort', '0002_urlshort_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='short',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
