# Generated by Django 3.2.8 on 2021-11-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0003_auto_20211121_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='short',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
