# Generated by Django 3.2.8 on 2021-12-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0004_alter_urlshort_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urlshort.urlshort')),
            ],
        ),
    ]
